version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: aoe-pl-db
    environment:
      POSTGRES_USER: aoepl
      POSTGRES_PASSWORD: aoeplpassword
      POSTGRES_DB: aoepl
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
    driver: local 