name: Check Eslint and Prettier

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install deps
        run: pnpm install

      - name: Format check
        run: pnpm run format:check
        if: always()

      - name: Lint
        run: pnpm run lint
        if: always()

      - name: Build
        run: pnpm run build
        env:
          AUTH_SECRET: dummy
          AUTH_DISCORD_ID: dummy
          AUTH_DISCORD_SECRET: dummy
          DATABASE_URL: dummy
        if: always()
